---
title: "STATPOP datasets"
subtitle: "Grid and raster"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(tidyverse, magrittr, scales,  
       DT, 
       raster, sf, tmap)

import::from("sjmisc", "frq")
tmap_mode("view")
```


```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)
```

<!-- ----------------------------------------------------- -->

# Geo 

```{r}
gg21 <- read_rds("data/BfS/gg21.Rds") %>% 
  st_transform(2056)

st_gg21 <- read_rds("data/swisstopo/st_gg21.Rds") %>% 
  st_transform(2056)
```

<!-- ----------------------------------------------------- -->

# STATPOP

Used to define `offset` for `st_make_grid`

```{r}
statpop_2020 <- read_delim("data-raw/ag-b-00.03-vz2020statpop/STATPOP2020.csv", 
                           delim = ";", escape_double = FALSE, trim_ws = TRUE)[] %>% 
  mutate_all(as.integer) %>% 
  dplyr::select(-X_KOORD, -Y_KOORD)
```

```{r}
offset <- statpop_2020 %>% 
  summarise(minX = min(E_KOORD),
            minY = min(N_KOORD),
            maxX = max(E_KOORD),
            maxY = max(N_KOORD))

# statpop_20 %>% slice(1:10) %>% View()

offset
```


```{r}
statpop_2020_pts <- statpop_2020 %>% 
  mutate(N_KOORD = N_KOORD + 50, 
         E_KOORD = E_KOORD + 50) %>% 
  st_as_sf(coords = c("E_KOORD", "N_KOORD"), 
           crs = 2056,
           remove = TRUE)
```

```{r}
statpop_2020_pts %>% 
  arrange(RELI) %>% 
  slice(1:100) %>% 
  qtm()
```


<!-- ----------------------------------------------------- -->

# STATPOP conversions 

## Grid (vector)

100m grid, with lower left corner defined using `STATPOP` cells and clippet using swisstopo municipality data. 

```{r}
grid_100m <- st_gg21 %>% 
  st_make_grid(cellsize = 100, 
               offset = c(offset$minX, offset$minY), 
               square = TRUE) %>% 
  st_sf() %>%
  st_filter(st_gg21)  %>%
  mutate(ID = row_number(),
         area = st_area(.)) %>% 
  relocate(ID, area) %>% 
  st_transform(2056)
```

```{r}
grid_100m %>% 
  arrange(ID) %>% 
  slice(1:100) %>% 
  qtm()
```

```{r}
# still with NAs!
grid_100m_data <- grid_100m %>% 
  st_join(statpop_2020_pts) 
```

```{r}
grid_100m_data %>% 
  filter(!is.na(RELI)) %>% 
  arrange(RELI) %>% 
  slice(1:100) %>% 
  qtm()

grid_100m_data %>% 
  filter(!is.na(RELI)) %>% 
  arrange(ID) %>% 
  slice(1:100) %>% 
  qtm()
```

## Raster

```{r}
r <- rasterFromXYZ(statpop_2020 %>% 
                     dplyr::select(-RELI),
                   crs = crs(st_gg21),
                   res = c(100, 100))

r@data@names <- names(statpop_2020)[4:ncol(statpop_2020)]

plot(r, "B20BTOT", colNA = "black")
```





https://www.google.com/search?q=r+create+a+grid+from+x+y

https://gis.stackexchange.com/questions/273233/create-spatial-polygon-grid-from-spatial-points-in-r

https://rspatial.org/raster/pkg/3-objects.html

https://www.rdocumentation.org/packages/sf/versions/0.9-7/topics/st_make_grid

https://gis.stackexchange.com/questions/273233/create-spatial-polygon-grid-from-spatial-points-in-r

